### ISSUE TITLE
MacOS: mv: rename BWT_Index/bwt_index to ./bwt_index: Is a directory

### ISSUE THREAD

**Issue by tseemann** [hsinnan75/MapCaller#9]
Because MacOS uses a case-insensitive file system, the following fails:

```
mv: rename BWT_Index/bwt_index to ./bwt_index: Is a directory
```

Can you call `bwt_index` `MapCaller-index` perhaps?

Or have a `make install` command which uses a `PREFIX ?= /usr/local/bin` setting and copies to `$(PREFIX)/` but I can still do `make install PREFIX=$HOME/bin` for example.

**Comment by tseemann** [comment]
MacOS test fail:

```
==> /usr/local/Cellar/mapcaller/0.9.9.6/bin/MapCaller -v 2>&1
==> /usr/local/Cellar/mapcaller/0.9.9.6/bin/bwt_index 2>&1
==> /usr/local/Cellar/mapcaller/0.9.9.6/bin/bwt_index /usr/local/Cellar/mapcaller/0.9.9.6/share/mapcaller/test/ref.fa /private/tmp/mapcaller-test-20190927-18114-1kvwqy/ref
[bwt_index] Pack FASTA... 0.00 sec
[bwt_index] Construct BWT for the packed sequence...
[BWTIncCreate] textLength=140000, availableWord=178360
[bwt_gen] Finished constructing BWT in 5 iterations.
[bwt_index] 0.02 seconds elapse.
[bwt_index] Update BWT... 0.00 sec
[bwt_index] Pack forward-only FASTA... 0.00 sec
[bwt_index] Construct SA from BWT and Occ... 0.00 sec
==> /usr/local/Cellar/mapcaller/0.9.9.6/bin/MapCaller -i ref -f /usr/local/Cellar/mapcaller/0.9.9.6/share/mapcaller/test/r1.fq -f2 /usr/local/Cellar/mapcaller/0.9.9.6/share/mapcaller/test/r2.fq -t 2
Load the genome index files...
Load the reference sequence (1 chromosome, total size = 70000 bp)...
Initialize the alignment profile...

0 paired-end reads have been processed in 0 seconds...
Error: brewsci/bio/mapcaller: failed
Failed executing:
/usr/local/Homebrew/Library/Homebrew/formula.rb:1914:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1851:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1851:in `system'
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-bio/Formula/mapcaller.rb:31:in `block in <class:Mapcaller>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1727:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:479:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1726:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:866:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1725:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1964:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1963:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1719:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:30:in `block in <main>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:29:in `<main>'
```

**Comment by hsinnan75** [comment]
I don't understand what you mean by "MacOS fails the command." I don't own a Mac PC. I'll try to get one and try on it. BWT_index is modified from BWA. You may use BWT index instead to build reference indexes and use them to run MapCaller.

**Comment by tseemann** [comment]
On MacOS, the filesystem does not treat upper-case and lower-case differently.
On MacOS,  `sinNAN` is the same as `sinnan`.
So you can't put `bwt_index` in the same folder where the folder `BWT_index` is, becase they have the same name in MacOS.

One solution is to arrange your code like this:
```
src
 ↳ MapCaller
 ↳ BWT_index
```

I think it would be cleaner to have a `bin` folder and copy the binaries into that, instead of the root folder

```
bin/
src/
 ↳ MapCaller/
 ↳ BWT_index/
test/
```

**Comment by hsinnan75** [comment]
Thanks for the explanation. I've followed your suggestion to rearrange the folder structure.

**Comment by tseemann** [comment]
I would also put all the MapCaller code in it's own folder
```
src/
 ↳ MapCaller/
 ↳ BWT_index/
 ↳ htslib/
```
but not very important.

**Comment by tseemann** [comment]
Don't forget to tag a new release `git tag v0.9.9.7 && git push --tags`

**Comment by pvanheus** [comment]
I made a conda recipe for 0.9.9.6 that works around this problem, so there is now a mapcaller package for MacOS and Linux in bioconda. When you release 0.9.9.7 the package will need to be reworked.

**Comment by hsinnan75** [comment]
Thank you both for your help.
